# Whether messages' JSON should be printed to console.
log-messages: true

# Whether special hover and click events should be attached to messages.
# Click event copies message's JSON to your clipboard.
# Hover event notifies about the click event.
# Special hover and click events will not be attached to messages that already contain either of the events.
# This option works only on 1.15 and above, and will be automatically disabled on lower versions.
attach-special-hover-and-click-events: true

# Messages that should be edited.
# For in-depth tutorial check here:
# https://github.com/jaqobb/message-editor#usage
message-edits:
- ==: MessageEdit
  message-before-pattern: '\{"extra":\[\{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"([a-zA-Z0-9_]{3,16}) joined the game"\}\],"text":""\}'
  message-after: '{"extra":[{"bold":true,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"$1 joined the game"}],"text":""}'
