# Update-related settings.
update:
  # Whether administration should be notified about plugin update.
  notify: true

# Whether special hover and click events should be attached to chat messages.
attach-special-hover-and-click-events: true

# Enabled packet listeners. You can disable the ones you do not use to save resources.
# NOTE: Each edit in this section requires a full server restart to take effect.
packet-listeners:
  chat: true
  kick: true
  disconnect: true
  bossbar: true
  scoreboard-title: true
  scoreboard-entry: true
  inventory-title: true
  inventory-item: true
  entity-name: true

# Messages that should be edited.
# For more in-depth tutorial check here:
# https://github.com/jaqobb/message-editor#usage
message-edits:
- ==: MessageEdit
  message-before-pattern: '\{"extra":\[\{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"([a-zA-Z0-9_]{3,16}) joined the game"\}\],"text":""\}'
  message-before-place: SYSTEM_CHAT
  message-after: §x§4§6§b§4§5§f$1 §fjoined the game
  message-after-place: ACTION_BAR
- ==: MessageEdit
  message-before-pattern: '\{"extra":\[\{"text":"You are (\d+) version\(s\) behind"\}\],"text":""\}'
  message-before-place: SYSTEM_CHAT
  message-after: '{"extra":[{"color":"green","text":"You are $1 version(s) behind. Consider updating."}],"text":""}'
- ==: MessageEdit
  message-before-pattern: '\{"extra":\[\{"text":"You are running the latest version"\}\],"text":""\}'
  message-before-place: SYSTEM_CHAT
  message-after: '{"extra":[{"color":"green","text":"You are up to date with the server version! :)"}],"text":""}'
