name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    #if: "!startsWith(${{ github.event.head_commit.message }}, '[CI-SKIP]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 8
      uses: actions/setup-java@v2
      with:
        java-version: 8.0.372+7
        distribution: adopt
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build shadowJar
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/*.jar
